# Generated by Django 2.1.3 on 2018-12-06 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loan_duration',
            field=models.DurationField(default=datetime.timedelta(14)),
        ),
    ]
