# Generated by Django 2.1.3 on 2018-12-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/static/img/placeholder.png', upload_to='items/'),
        ),
    ]
