# Generated by Django 2.1.4 on 2018-12-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/placeholder.png', upload_to='items'),
        ),
        migrations.AddField(
            model_name='item',
            name='loan_duration',
            field=models.DurationField(default=datetime.timedelta(14)),
        ),
    ]
