# Generated by Django 2.2 on 2019-09-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190407_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
