# Generated by Django 2.2 on 2019-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
