# Generated by Django 2.1.2 on 2018-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreservation',
            name='reservation_ends',
            field=models.DateTimeField(null=True),
        ),
    ]
