# Generated by Django 2.1.4 on 2018-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_itemreservation_reservation_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemloan',
            name='due_on',
            field=models.DateTimeField(null=True),
        ),
    ]
