# Generated by Django 2.2 on 2019-04-08 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clients_to_users(apps, schema_editor):
    """Migrate Client objects to User objects for ItemReservations and ItemLoans"""
    User = apps.get_model('users', 'User')
    ItemLoan = apps.get_model('loans', 'ItemLoan')
    ItemReservation = apps.get_model('loans', 'ItemReservation')

    for model in (ItemLoan, ItemReservation):
        for obj in model.objects.all():
            client = obj.client
            if client.user:
                user = client.user
            else:
                user, created = User.objects.get_or_create(
                    email=client.email,
                    defaults={
                        'first_name': client.first_name,
                        'last_name': client.last_name,
                    },
                )
            obj.user = user
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_itemloan_due_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemloan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemloan',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            clients_to_users,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='itemloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='itemloan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='itemreservation',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
